export const ADD_BUN_BURGER = 'ADD_BUN_BURGER';
export const ADD_INGREDIENT_BURGER = 'ADD_INGREDIENT_BURGER';
export const REMOVE_INGREDIENT_BURGER = 'REMOVE_BUN_BURGER';
export const REMOVE_ALL_INGREDIENTS_BURGER = 'REMOVE_ALL_INGREDIENTS_BURGER'
